export { default as Footer } from "./footer";
export { default as Coupons } from "./coupons";
export { default as Event } from "./event";
export { default as Registr } from "./registration";
export { default as RegistrSuccess } from "./registsuccess";
export { default as Category } from "./category";
export { default as Best } from "./best";
export { default as Product } from "./product";
export { default as Carousel } from "./carousel";
